# Generated by Django 4.2.16 on 2024-09-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
