# Generated by Django 4.2.16 on 2024-09-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataF', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Lname',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Name',
            new_name='name',
        ),
    ]
